ALTER TABLE clients ADD COLUMN IF NOT EXISTS razao_social text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cnpj text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS telefone text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS whatsapp text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS email_faturamento text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS endereco text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cidade text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS uf text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cep text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS contato_responsavel text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cargo_responsavel text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS prazo_pagamento text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS prazo_envio_docs text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS faturamento_tipo_padrao text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS instrucoes_faturamento text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS exige_aceite_formal boolean NOT NULL DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS exige_nota_fiscal_detalhada boolean NOT NULL DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS exige_declaracao_art299 boolean NOT NULL DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS exige_comprovante_assinado boolean NOT NULL DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS exige_print_diario boolean NOT NULL DEFAULT false;
